### ISSUE TITLE
Congrats + encouragement to push the idea

### ISSUE THREAD

**Issue by MichelML** [drf-psq/drf-psq#4]
Just wanted to say this is one of the cleanest way of augmenting viewsets I've seen and you should keep pushing the idea forward (perhaps more actively ;) )

Thanks a lot for this amazing pattern fitting DRF so well :+1:

**Comment by AminHP** [comment]
Hi @MichelML, thank you! We really appreciate your compliment :)

We used this library in some projects and didn't find any more ideas to add. Besides, we changed our field of work from Software Engineering to AI and DevOps. So, we probably won't be able to extend it. However, we welcome new suggestions and ideas. So if you have something specific on your mind, we would love to hear it and collaborate.

**Comment by MichelML** [comment]
alright, will do, let's close this :+1:
